
CREATE USER AT_KUTUPHANE IDENTIFIED BY "123456";

GRANT CONNECT TO AT_KUTUPHANE;
GRANT RESOURCE TO AT_KUTUPHANE;
GRANT UNLIMITED TABLESPACE TO AT_KUTUPHANE;
GRANT CREATE VIEW TO AT_KUTUPHANE;
GRANT CREATE SEQUENCE TO AT_KUTUPHANE;
GRANT CREATE PROCEDURE TO AT_KUTUPHANE;
GRANT CREATE TRIGGER TO AT_KUTUPHANE;

ALTER USER AT_KUTUPHANE DEFAULT TABLESPACE USERS;
ALTER USER AT_KUTUPHANE TEMPORARY TABLESPACE TEMP;

BEGIN
    DBMS_OUTPUT.PUT_LINE('==========================================');
    DBMS_OUTPUT.PUT_LINE('AT_KUTUPHANE KULLANICISI OLUŞTURULDU!');
    DBMS_OUTPUT.PUT_LINE('==========================================');
    DBMS_OUTPUT.PUT_LINE('Kullanıcı Adı: AT_KUTUPHANE');
    DBMS_OUTPUT.PUT_LINE('Şifre: Kutuphane123!');
    DBMS_OUTPUT.PUT_LINE('==========================================');
    DBMS_OUTPUT.PUT_LINE('SONRAKİ ADIM:');
    DBMS_OUTPUT.PUT_LINE('1. Oracle bağlantınızı kapatın');
    DBMS_OUTPUT.PUT_LINE('2. AT_KUTUPHANE kullanıcısıyla bağlanın');
    DBMS_OUTPUT.PUT_LINE('3. 2_Ana_Sistem.sql dosyasını çalıştırın');
    DBMS_OUTPUT.PUT_LINE('==========================================');
END;
/ 
